name: CMake

on:

  push:
    paths:
    - src/**
    - "**/CMakeLists.txt"
    - "CMakePresets.json"
    - .github/workflows/cmake.yml
    - vcpkg.json
    - "!**/Makefile*"

  pull_request:
    paths:
    - src/**
    - "**/CMakeLists.txt"
    - "CMakePresets.json"
    - .github/workflows/**
    - .github/workflows/cmake.yml
    - vcpkg.json
    - "!**/Makefile*"

jobs:
  mingw:
    name: Windows MSYS2 (${{ matrix.build.name }} ${{ matrix.target.name }})

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    strategy:
      fail-fast: false
      matrix:
        build:
        - name: Regular
          preset: regular
          target: install/strip
        - name: Debug
          preset: debug
          target: install
        - name: Dev
          preset: experimental
          target: install
        target:
        - name: x86
          msystem: MINGW32
            prefix: mingw-w64-i686
            toolchain: cmake/flags-gcc-i686.cmake
        - name: x64
          msystem: MINGW64
            prefix: mingw-w64-x86_64
            toolchain: cmake/flags-gcc-x86_64.cmake

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        path-type: inherit
        update: true
        msystem: ${{ matrix.target.msystem }}
        install: >-
          ${{ matrix.target.prefix }}-ninja
          ${{ matrix.target.prefix }}-gcc
          ${{ matrix.target.prefix }}-clang
          ${{ matrix.target.prefix }}-pkg-config
          ${{ matrix.target.prefix }}-openal
          ${{ matrix.target.prefix }}-freetype
          ${{ matrix.target.prefix }}-SDL2
          ${{ matrix.target.prefix }}-zlib
          ${{ matrix.target.prefix }}-libpng
          ${{ matrix.target.prefix }}-libvncserver
          ${{ matrix.target.prefix }}-winpthreads
    - uses: actions/checkout@v2
    - name: Configure CMake
      run: >-
        cmake -S . -B build -G "MSYS Makefiles"
        --preset ${{ matrix.build.preset }}
        -D CMAKE_TOOLCHAIN_FILE=${{ matrix.target.toolchain }}
        -D CMAKE_INSTALL_PREFIX=./build/artifacts
        -D VNC=OFF
    - name: Build
      run: cmake --build build --target ${{ matrix.build.target }}
    - uses: actions/upload-artifact@v2
      with:
        name: '86Box-${{ matrix.build.name }}-MSYS2-${{ matrix.target.name }}-${{ github.sha }}'
        path: build/artifacts/bin/**

  vs2019:
    name: VS2019 ${{ matrix.build.name }} ${{ matrix.target-arch }} build (${{ matrix.toolset }})

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build:
        - name: Debug
          dev-build: off
          new-dynarec: off
          type: Debug
        - name: Dev
          dev-build: on
          new-dynarec: on
          type: Debug
        target-arch: ['Win32', 'x64', 'ARM64']
        toolset: ['clangcl']
        exclude:
          - target-arch: 'ARM64'
            build:
              new-dynarec: off

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: build/vcpkg_installed
        key: vcpkg-${{ hashFiles('vcpkg.json') }}-${{ matrix.target-arch }}
    - name: Configure CMake
      run: >-
        cmake -S . -B build
        -G "Visual Studio 16 2019" -A ${{ matrix.target-arch }} -T ${{ matrix.toolset }}
        -D CMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake
        -D CMAKE_INSTALL_PREFIX=./build/artifacts
        -D DEV_BRANCH=${{ matrix.build.dev-build }}
        -D NEW_DYNAREC=${{ matrix.build.new-dynarec }}
        -D VNC=OFF
    - name: Build
      run: cmake --build build --config ${{ matrix.build.type }} --target install
    - uses: actions/upload-artifact@v2
      with:
        name: '86Box-${{ matrix.build.name }}-VS2019-${{ matrix.target-arch }}-${{ matrix.toolset }}-${{ github.sha }}'
        path: build/artifacts/bin/**

  linux:
    name: "Linux GCC 11"

    runs-on: ubuntu-latest
    strategy:
      matrix:
        build:
        - name: Regular
          preset: regular
          target: install/strip
        - name: Debug
          preset: debug
          target: install
        - name: Dev
          preset: experimental
          target: install

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt install gcc-11 g++-11 libfreetype-dev libsdl2-dev libpng-dev libopenal-dev libc6-dev
      - name: Configure CMake
        run: >-
        cmake -S . -B build --preset ${{ matrix.build.preset }}
          -D CMAKE_INSTALL_PREFIX=./build/artifacts
        -D CMAKE_TOOLCHAIN_FILE=./cmake/flags-gcc-i686.cmake
          -D CMAKE_C_COMPILER=gcc-11 -D CMAKE_CXX_COMPILER=g++-11
      - name: Build
      run: cmake --build build --target ${{ matrix.build.target }}
    - uses: actions/upload-artifact@v2
      with:
        name: '86Box-${{ matrix.build.name }}-ubuntu-${{ github.sha }}'
        path: build/artifacts/bin/**

  macos:
    name: "macOS 11"

    runs-on: macos-11
    strategy:
      matrix:
        build:
        - name: Regular
          preset: regular
          target: install/strip
        - name: Debug
          preset: debug
          target: install
        - name: Dev
          preset: experimental
          target: install

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install freetype sdl2 libpng openal-soft
      - name: Configure CMake
        run: >-
        cmake -S . -B build --preset ${{ matrix.build.preset }}
          -D CMAKE_INSTALL_PREFIX=./build/artifacts
        -D CMAKE_TOOLCHAIN_FILE=./cmake/flags-gcc-i686.cmake
      - name: Build
      run: cmake --build build --target ${{ matrix.build.target }}
    - uses: actions/upload-artifact@v2
      with:
        name: '86Box-${{ matrix.build.name }}-macos11-${{ github.sha }}'
        path: build/artifacts/bin/**
